-- COMANDO DTL (linguagem de transação de dados)------------------------------------
/* ELE SE RESUME A 3 TIPOS DE COMANDO BEGIN TRAN OU TRANSACTION, COMMIT, ROLLBACK

COMMIT: SALVARA A ALTERAÇÃO NA BASE DE DADOS E FECHARÁ A TRANSAÇÃO
ROOLBACK: IRÁ DESFAZER A ALTERAÇÃO REALIZADA E FECHARÁ A TRANSAÇÃO

SINTAXE:
     BEGIN TRAN 
		COMANDO SQL
     COMMIT OU ROLLBACK    

*/ 


SELECT *
FROM TB_DML

/*TESTANDO UPDATE*/
BEGIN TRAN 
UPDATE TB_DML
SET DTNASC = '1995-06-15'
WHERE NOME = 'PESSOA_D'
-- DEPOIS DE EXECUTAR O BEGIN TRAN, AI VOCÊ ESCOLHE SE VAI DA UM COMMIT OU UM ROOLBACK
-- OS DOIS FINALIZAM A TRANZAÇÃO SE CASO NÃO EXECUTAR ESTES COMANDOS A TRANZAÇÃO FICA ABERTA
-- E OS DADOS ESTÃO SALVOS APENAS EM MEMÓRIA, FALTA DA O COMMIT OU ROLLBACK PARA
-- SER REALMENTE FINALIZADO.

COMMIT -- SALVAR NA TABELA DEFINITIVAMENTE
ROLLBACK -- DESFAZER A OPERAÇÃO EXECUTADA


/*TESTANDO DELETE*/
BEGIN TRAN
DELETE FROM TB_DML

ROLLBACK -- DESFAZER A OPERAÇÃO EXECUTADA

/*TESTANDO TRUNCATE*/

BEGIN TRAN
TRUNCATE TABLE TB_DML

ROLLBACK -- DESFAZER A OPERAÇÃO EXECUTADA


-- SÓ USAMOS O ROLLBACK OU COMMIT QUANDO TEM UMA TRANSAÇÃO ABERTA
-- TODA VEZ QUE ABRIR UMA TRAZAÇÃO SEMPRE TEM QUE FECHAR.