---------- COMANDO DQL (LINGUAGEM DE CONSULTAS DE DADOS) ------------------
/*
    SINTAXE:
	SELECT * FROM tabela, view ou function


*/

/*EXECUTANDO SELECT EXIBINDO O VALOR DE UMA VARIÁVEL*/
-- DECLARE SERBE PARA DECLARAR UMA VARIAVEL
DECLARE @V TINYINT
SET @V = 50

SELECT @V

/*EXECUTANDO SELECT SEM NENHUMA TABELA*/
SELECT 500

/*SELECIONANDO TODOS OS REGISTROS DA TABELA E LISTANDO TODAS AS COLUNAS*/
SELECT *
FROM TB_DML

/*FILTRANDO POR 1 COLUNA E EXIBINDO APENAS 2 COLUNAS DA TABELA*/
SELECT 
NOME, 
DTNASC
FROM TB_DML
WHERE SEXO = 'F'

/*FILTRANDO POR 2 COLUNAS*/
SELECT * 
FROM TB_DML
WHERE DTNASC > '1999-10-25'
AND SEXO =	'F'

